aws_region:                     us-east-2
aws_access_key_id:
aws_secret_access_key:
db_host:                        postgres
db_port:                        5432
db_database:                    kumquat
db_username:                    postgres
db_password:                    postgres
downloader_url:
downloader_user:
downloader_password:
elasticsearch_endpoint:         http://elasticsearch:9200
elasticsearch_index:            kumquat
iiif_url:                       http://cantaloupe:8182/iiif/2
image_server_api_endpoint:      http://cantaloupe:8182
image_server_api_user:          kumquat
image_server_api_secret:        secret
mail:
  from: "kumquat@example.org"
  reply_to: "kumquat@example.org"
medusa_url:                     http://mockdusa:4567
medusa_user:                    medusa
medusa_secret:                  secret
medusa_admins_group:
  name: Library Medusa Admins
  permissions:
    - collections.modify
    - elements.modify
    - items.modify
    - metadata_profiles.modify
    - settings.modify
    - collections.purge_items
medusa_superusers_group:
  name: Library Medusa Super Admins
medusa_users_group:
  name: Library Medusa Users
  permissions:
    - collections.modify
    - items.modify
medusa_s3_endpoint:             http://minio:9000
medusa_s3_access_key_id:        MinioUser
medusa_s3_secret_access_key:    OpenSesame
medusa_s3_bucket:               medusa
metadata_gateway_url:           https://metadata.library.illinois.edu
s3_endpoint:                    http://minio:9000
s3_bucket:                      kumquat
secret_key_base:                whateverdoesntmatter
